# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.12
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: walksanatora
book_id: hexcasting:thehexbook
default_branch: master
github_repo: Hextweaks
gradle_mod_version_key: mod_version
hexdoc_mod_plugin_classname: HextweaksModPlugin
hexdoc_plugin_classname: HextweaksPlugin
java_lang:
    ext: kt
    src: kotlin
java_package: net/walksanator/hextweaks
mod_display_name: HexTweaks
modid: hextweaks
multiloader: true
package_export_root: doc/src/hexdoc_hextweaks/_export
package_name: hexdoc-hextweaks
package_slug: hexdoc_hextweaks
package_src: doc/src/hexdoc_hextweaks
pages_url: https://walksanatora.github.io/HexTweaks/
pattern_regex:
    per_world_value: 'true'
    regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: casting/PatternRegistry.kt
