# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.12
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: Walksantor
book_id: hextweaks:thetweakedbook
default_branch: master
github_repo: HexTweaks
gradle_mod_version_key: mod_version
hexdoc_mod_plugin_classname: HextweaksModPlugin
hexdoc_plugin_classname: HextweaksPlugin
java_lang:
    ext: kt
    src: kotlin
java_package: net/walksanator/hextweaks
mod_display_name: HexTweaks
modid: hextweaks
multiloader: true
package_export_root: doc/src/hexdoc_hextweaks/_export
package_name: hexdoc-hextweaks
package_slug: hexdoc_hextweaks
package_src: doc/src/hexdoc_hextweaks
pages_url: https://walksantor.github.io/HexTweaks/
pattern_regex:
    per_world_value: 'true'
    regex: HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*modLoc\("(?P<name>[^"]+)"\)[^;]+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:[^;]*(?P<is_per_world>true)\);)?
pattern_registry: registry/patterns/PatternRegister.kt
