modid = "hextweaks"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "master"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    "{_fabric.src}/main/resources",
    { path="{^_fabric.src}/generated/resources", required=false },
    "{_forge.src}/main/resources",
    { path="{^_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hextweaks/_export/generated"

[template]
icon = "icon.png"
include = [
    "hextweaks",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "HexTweaks"
author = "walksanatora"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='pattern\(HexDir\.(?P<startdir>\w+),\s*"(?P<signature>[qweasd]+)",\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*.*\)' }
_per_world_value = "true"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/casting/PatternRegistry.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
package = "{src}/main/java/net/walksanator/hextweaks"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/net/walksanator/hextweaks/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/java/net/walksanator/hextweaks/forge"
